User.create!([
  {email: "jay@email.com", password: "password", encrypted_password: "$2a$10$2MI2TGQLh0Kx8img3N9XquQqu8jhYCCv8x7OtbbNOWoUXSqybgrA2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 7, current_sign_in_at: "2016-01-13 17:27:02", last_sign_in_at: "2016-01-12 17:26:38", current_sign_in_ip: "::1", last_sign_in_ip: "::1", name: "Jay", role: "admin"},
  {email: "nick@email.com", encrypted_password: "$2a$10$LslPVeWHiPv.55dbSevopey84l2AHCbphSGirpgK.XXdFSi9Ftw2O", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-01-11 10:47:01", last_sign_in_at: "2016-01-11 10:47:01", current_sign_in_ip: "::1", last_sign_in_ip: "::1", name: nil, role: nil},
  
])
Performer.create!([
  {name: "Joe Rogan", description: "Joe Rogan is an American stand-up comedian, podcaster, and color commentator. He is also a former actor, host, and mixed martial artist but is perhaps best known for his podcast titled The Joe Rogan Experience, performing stand-up comedy, color commentating for the Ultimate Fighting Championship (UFC), and hosting former reality shows Fear Factor and Joe Rogan Questions Everything.", image: "https://pbs.twimg.com/profile_images/552307347851210752/vrXDcTFC.jpeg"},
  {name: "Ari Shaffir", description: "Ari Shaffir is an actor and producer, known for InAPPropriate Comedy (2013), Ari Shaffir: Paid Regular (2015) and Chronic-Con, Episode 420: A New Dope (2015).", image: "http://judygold.com/wp-content/uploads/2015/12/Ari-Shaffir1.jpg"},
  {name: "Louis CK", description: " Louis C.K. is an American comedian, actor, writer, producer, director, and editor. He is the creator, star, writer, director, executive producer, and primary editor of the acclaimed FX comedy-drama series Louie. C.K. is known for his use of observational, self-deprecating, dark and vulgar humor in his stand-up career.", image: "http://www.austinchronicle.com/binary/1157/scaled.louisck.png"},
  {name: "Sam Kinison", description: "Sam Kinison, an American stand-up comedian and actor. He was known for his intense, harsh and politically incorrect humor. A former Pentecostal preacher, he performed stand-up routines that were most often characterized by an intense style, similar to charismatic preachers, and punctuated by his trademark scream.", image: "http://www.champcomedyblog.com/wp-content/uploads/2013/11/KINISON.jpg"},
  {name: "Bill Hicks", description: "Bill Hicks, an American stand-up comedian, social critic, satirist, and musician. His material, encompassing a wide range of social issues including religion, politics, and philosophy, was controversial, and often steeped in dark comedy. He criticized consumerism, superficiality and banality within the media and popular culture, which he characterized as oppressive tools of the ruling class that keep people \"stupid and apathetic\".", image: "http://myspiltmilk.com/sites/default/files/main-image/untitled-1.jpeg"},
  {name: "Bill Burr", description: "Bill Burr is an American comedian, writer, and actor. He is best known for his stand-up comedy specials. He is also known for being the host of Bill Burr's Monday Morning Podcast, playing Patrick Kuby in the AMC crime drama series Breaking Bad, and starring in the Netflix animated sitcom F Is for Family as Frank Murphy. In 2013, The New York Times wrote that Burr \"has been one of the funniest, most distinctive voices in the country for years.\"", image: "http://www.thewrap.com/wp-content/uploads/2014/12/Bill-Burr-Netflix-special.jpg"},
  {name: "Tom Segura", description: "Tom Segura is an American comedian from Cincinnati, Ohio. He currently lives in Los Angeles, California.", image: "http://tomseguracom.ipage.com/wp-content/uploads/2014/03/TOM_Slide_face.jpg"}
])
Show.create!([
  {name: "Shiny Happy Jihad", image: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c6/Shiny_Happy.jpg/220px-Shiny_Happy.jpg", description: "Funny show!", venue_id: 5, performer_id: 8, start_time: "2016-07-11 21:00:00", end_time: "2016-07-11 22:30:00", capacity: 400},
  {name: "Passive Aggressive", image: "http://images.bwwstatic.com/columnpic6/9545A560-92A7-955A-76E134A6B9E99AE3.jpg", description: "Passive aggressive comedy", venue_id: 6, performer_id: 9, start_time: "2016-07-06 21:00:00", end_time: "2016-07-06 22:30:00", capacity: 200},
  {name: "Talking Monkeys in Space ", image: "http://ecx.images-amazon.com/images/I/61oIl076-OL.jpg", description: "dasf", venue_id: 5, performer_id: 8, start_time: "2016-07-12 21:00:00", end_time: "2016-07-12 22:30:00", capacity: 400},
  {name: "Hilarious ", image: "https://upload.wikimedia.org/wikipedia/en/e/e8/Hilarious.jpg", description: "Louis talks about \"Being Single Again\", \"Other People's Kids\"  and his own in this new Hilarious hour", venue_id: 3, performer_id: 4, start_time: "2016-08-05 21:00:00", end_time: "2016-08-05 22:00:00", capacity: 200},
  {name: "Louder Than Hell ", image: "http://cps-static.rovicorp.com/3/JPG_400/MI0003/328/MI0003328987.jpg?partner=allrovi.com", description: "Louder Than Hell is the debut comedy album by Sam Kinison that was released in 1986.", venue_id: 10, performer_id: 11, start_time: "2016-04-13 23:00:00", end_time: "2016-04-13 00:00:00", capacity: 250},
  {name: "Relentless ", image: "http://ecx.images-amazon.com/images/I/51RA2KGJ03L.jpg", description: "Relentless is a live album by stand-up comedian and satirist Bill Hicks. It was his second CD release, and his last one before his death from pancreatic cancer in February 1994.", venue_id: 9, performer_id: 12, start_time: "2016-04-07 21:30:00", end_time: "2016-04-07 22:30:00", capacity: 300},
  {name: "I'm Sorry You Feel That Way", image: "http://ia.media-imdb.com/images/M/MV5BMTk0MzI5MjAxNV5BMl5BanBnXkFtZTgwNDY1NzA0NDE@._V1__SX1234_SY615_.jpg", description: "Bill Burr, comedian, holds a show in front of an audience.", venue_id: 5, performer_id: 13, start_time: "2016-04-24 20:30:00", end_time: "2016-04-24 22:00:00", capacity: 500},
  {name: "Completely Normal", image: "http://ia.media-imdb.com/images/M/MV5BMTcyODE0Mzk1Nl5BMl5BanBnXkFtZTgwMDk4ODE0NDE@._V1_SY317_CR6,0,214,317_AL_.jpg", description: "Levelheaded stand-up Tom Segura shares offhand on hotels and opens up about his hobbies and digestive ailments in this comedy special", venue_id: 7, performer_id: 14, start_time: "2016-04-20 20:00:00", end_time: "2016-04-20 21:00:00", capacity: 200}
])
Venue.create!([
  {name: "Usher Hall", description: "The Usher Hall is a 5 star concert hall, situated on Lothian Road, in the west end of Edinburgh, Scotland. It has hosted concerts and events since its construction in 1914 and can hold approximately 2,200 people in its recently restored auditorium, which is well loved by performers due to its acoustics. The Hall is flanked by The Royal Lyceum Theatre on the right and The Traverse Theatre on the left. Historic Scotland has registered the Hall with Category A listed building status.", image: "http://s0.geograph.org.uk/photos/14/99/149973_48fb27a0.jpg", location: "Lothian Road", capacity: nil},
  {name: "Kings Theatre", description: "The King's Theatre was opened in 1906 and stands on a prominent site on Leven Street in Edinburgh. It is one of Scotland's historic and most important theatres. It plays a vital role in today's theatre industry as much as it has done in its 100 years of service to Edinburgh theatre patrons.", image: "http://www.theatresonline.com/theatres/edinburgh-theatres/the-kings-theatre/images/kings-theatre.jpg", location: "2 Leven St, Edinburgh EH3 9LQ", capacity: nil},
  {name: "Gilded Balloon", description: "The Gilded Balloon is one of the Edinburgh Festival Fringe's best-known venues, established by Karen Koren in 1986 in Edinburgh's Cowgate. When a fire destroyed the original premises, Teviot Row House in Bristo Square became the Gilded Balloon's main venue.", image: "http://www.gildedballoon.co.uk/wp-content/uploads/2014/07/GB-crop.jpg", location: "25 Greenside Ln, Edinburgh EH1 3AA, United Kingdom", capacity: nil},
  {name: "Assembly Rooms", description: "The Assembly Rooms are in central Edinburgh. Originally solely a meeting place for social gatherings, it is now also used as an arts venue and for public events, including the Edinburgh Festival Fringe and the Hogmanay celebrations. There are four rooms that are used year-round and are available for private functions: Music Hall, Ballroom, Supper Room and Edinburgh Suite. The building is protected as a category A listed building as \"an outstanding example of the late 18th century public building, continuing its original use\"", image: "http://www.edinburgharchitecture.co.uk/images/jpgs/assembly-rooms-edinburgh-p120613-p2.jpg", location: "54 George St, Edinburgh EH2 2LR, United Kingdom", capacity: nil},
  {name: "Pleasance Dome", description: "Since 2000 the Pleasance Dome has been the hub of the now-famous Bristo Square, with the best comedy and theatre in 5 venues all under one roof. The legendary Pleasance atmosphere runs late in to the night.", image: "https://c2.staticflickr.com/6/5539/12524175273_b00b4a0acd_b.jpg", location: "Pleasance Dome, 1 Bristo Pl, Edinburgh EH8 9AL, United Kingdom", capacity: nil},
  {name: "Assembly on the Mound", description: "The magnificent venue atop the Mound is the most prestigious venue on the Fringe and hosts the finest drama, music and comedy. Entrance and box office through New College Quad off Mound Place. The venue houses three spaces; the Main Hall, Rainy Hall and Baillie Room.", image: "http://ispneconference.com/wp-content/uploads/2014/09/Assembly.jpg", location: "Mound Place, EH1 2LU", capacity: nil}
])
